project/apps/users/urls.py
from django.urls import path
from django.contrib.auth.views import auth_login

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.index, name="index"),
    path('logout/', views.logout, name='logout'),
    path('authenticate/', views.login, name='login'),
    path('register/', views.register, name='register')
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.shortcuts import render
from django.http import request


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cources/', include("cources.urls", namespace="cources")),
    path('users/', include("users.urls", namespace='users')),
    path('calendar/', include("fullcalendar.urls", namespace="fullcalendar")),
    path('api-auth/', include("rest_framework.urls", namespace="rest_framework")),
    path('', include("appearance.urls", namespace="appearance")),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]

project/templates/bootstrap4/base.html
{% extends 'bootstrap4/include.html' %}

{% load static %}



{% block nav %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'cources:index' %}">EDEN</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'cources:index' %}">Главная<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Календарь
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'fullcalendar:index' %}">Календарь</a>
          <a class="dropdown-item" href="/calendar/events/">Мои события</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="hidden" readonly>
        {% if user.is_authenticated %}
        <a class="nav-link" href="#">Hello, {{ user.username }}</a>
        <a class="btn btn-outline-success my-2 my-sm-0" type="button" href="{% url 'users:logout' %}">Выйти</a>
        {% else %}
         <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
        <a class="btn btn-outline-success my-2 my-sm-0" type="button" href="{% url 'users:index' %}">Войти</a>
        {% endif %}
    </form>
  </div>
</nav>

{% endblock nav %}

<div class="wrapper">
{% block header %}
{% endblock header %}

{% block sidebar1 %}
<div id="sidebar1" class="aside">

    <h3>Head</h3>
    <ul>
        <li>Item</li>
        <li>Item</li>
        <li>Item</li>
        <li>Item</li>
        <li>Item</li>
        <li>Item</li>
    </ul>

</div>
{% endblock sidebar1 %}


    {% block sidebar2 %}
<div id="sidebar2" class="aside">

    <h2>1914 translation by H. Rackham</h2>
                <p>It is a long established fact that a reader will be distracted by the readable
                content of a page when looking at its layout.</p>
                <h3>Options</h3>
                <ul>
                    <li>Item1</li>
                    <li>Item2</li>
                    <li>Item3</li>
                </ul>

</div>
{% endblock sidebar2 %}

    <div id="content">
    {% block content %}
    {% endblock content %}
    </div>

</div>
{% block footer %}
{% endblock footer %}