project/apps/fullcalendar/urls.py
from django.urls import path, include

from rest_framework import routers

from . import views

app_name = 'fullcalendar'

router = routers.DefaultRouter()
router.register('events', views.EventViewSet, basename="events")
router.register('resources', views.ResourceViewSet, basename="resources")

urlpatterns = [
    path('', views.index, name='index'),
    path('', include(router.urls)),

    path('add_event/', views.add_event, name="add_event"),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.shortcuts import render
from django.http import request


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cources/', include("cources.urls", namespace="cources")),
    path('users/', include("users.urls", namespace='users')),
    path('calendar/', include("fullcalendar.urls", namespace="fullcalendar")),
    path('api-auth/', include("rest_framework.urls", namespace="rest_framework")),
    path('', include("appearance.urls", namespace="appearance")),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]

project/apps/fullcalendar/models.py
from django.db import models


class Event(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True, verbose_name='title')
    start = models.DateTimeField()
    end = models.DateTimeField()
    allDay = models.BooleanField(default=False)
    description = models.TextField(blank=True, null=True)
    resourceId = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-start', '-end', 'title')


class Resource(models.Model):
    id = models.CharField(primary_key=True, max_length=50)
    title = models.CharField(max_length=100, blank=True, null=True, verbose_name='title')
    eventBackgroundColor = models.CharField(max_length=50, default='#3788d8')
    eventTextColor = models.CharField(max_length=50, default='#fff')
    eventClassNames = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.id

    class Meta:
        ordering = ('id',)

project/apps/fullcalendar/views.py
from django.shortcuts import render
from django.http import HttpResponse

from rest_framework import generics, viewsets

from .models import Event, Resource
from .serializers import EventSerializer, ResourceSerializer


def index(request):
    template_name = 'fullcalendar/fullcalendar.html'
    return render(request, template_name)


def add_event(request):
    return HttpResponse(request.POST)


class EventViewSet(viewsets.ModelViewSet):
    queryset = Event.objects.all()
    serializer_class = EventSerializer


class ResourceViewSet(viewsets.ModelViewSet):
    queryset = Resource.objects.all()
    serializer_class = ResourceSerializer

project/apps/fullcalendar/templates/fullcalendar/fullcalendar.html
{% extends 'appearance/index.html' %}

{% load static %}

{% load bootstrap4 %}

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% block header %}
<h1>Ближайшие события</h1>
{% endblock header %}


{% block content %}
<div id="calendar"></div>

<div id="dialog">
    <form method="post" action="{% url 'fullcalendar:add_event' %}" class="form">
        {% csrf_token %}
        <div class="from-group">
            <label for="title">Заголовок</label>
            <textarea id="title" name="title" autocomplete="off"
                      class="form-control"></textarea>
        </div>
        <div class="from-group">
        <label for="start">Начало</label>
            <input type="text" id="start" name="start"
                   class="datetimepicker form-control"
                   autocomplete="off">
        </div>
        <div class="form-group">
            <label for="end">Конец</label>
            <input type="text" id="end" name="end"
               class="datetimepicker form-control"
               autocomplete="off">
        </div>
        <div class="form-group">
            <label for="description">Описание</label>
            <p></p>
            <textarea id="description" name="description"
                  autocomplete="off"></textarea>
            <small id="descriptionHelp" class="form-text text-muted">Необязательное поле</small>
        </div>

        {% buttons %}
        <button type="submit" class="btn btn-primary">OK</button>
        {% endbuttons %}
    </form>
</div>

{% endblock content %}