project/apps/users/urls.py
from django.urls import path
from django.contrib.auth.views import auth_login

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.index, name="index"),
    path('logout/', views.logout, name='logout'),
    path('authenticate/', views.login, name='login'),
    path('register/', views.register, name='register')
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.shortcuts import render
from django.http import request


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cources/', include("cources.urls", namespace="cources")),
    path('users/', include("users.urls", namespace='users')),
    path('calendar/', include("fullcalendar.urls", namespace="fullcalendar")),
    path('api-auth/', include("rest_framework.urls", namespace="rest_framework")),
    path('', include("appearance.urls", namespace="appearance")),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]

project/apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class EdenUser(AbstractUser):
    pass

project/apps/users/forms.py
from django import forms

from .models import EdenUser


class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = EdenUser
        fields = ['username', 'password1', 'password2', 'first_name', 'last_name', 'email']

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['username'].label = 'Имя пользователя'
        self.fields['password1'].label = 'Пароль'
        self.fields['password2'].label = 'Повторите пароль'
        self.fields['first_name'].label = 'Имя'
        self.fields['last_name'].label = 'Фамилия'
        self.fields['email'].label = 'Почта'

    def clean(self):
        username = self.cleaned_data['username']
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        email = self.cleaned_data['email']
        if EdenUser.objects.filter(username=username).exists():
            raise forms.ValidationError('Логин занят')
        if EdenUser.objects.filter(email=email).exists():
            raise forms.ValidationError('Данная почта уже зарегистрирована')
        if password1 != password2:
            raise forms.ValidationError('Ваши пароли не совпадают')

project/apps/users/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.views import auth_login, auth_logout
from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.http import Http404, HttpResponse, HttpResponseRedirect

from .forms import RegisterForm


def index(request):
    template_name = 'users/login.html'
    return render(request, template_name)


def login(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        auth_login(request, user)
        return redirect('/')
    else:
        return HttpResponse('Аутентификация не пройдена')


def logout(request):
    auth_logout(request)
    return redirect('/')


def register(request):
    if request.method != 'POST':
        form = RegisterForm()
    else:
        form = RegisterForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            new_user.set_password(request.POST['password1'])
            new_user.save()
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'],
                                              )
            auth_login(request, authenticated_user)
            return HttpResponseRedirect(reverse('cources:index'))
    context = {'form': form}
    template = 'users/register.html'
    return render(request, template, context)

project/apps/users/templates/users/login.html
{% extends 'appearance/base.html' %}

{% load static %}

{% block main %}

<form class="form-signin" style="margin:30%;" method="post" action="{% url 'users:login' %}">
  {% csrf_token %}
  <img class="mb-4" src="/docs/4.4/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
  <h1 class="h3 mb-3 font-weight-normal">Пожалуйста, войдите в свою учётную запись</h1>
  <label for="username" class="sr-only">Логин</label>
  <input type="text" id="username" class="form-control" placeholder="Login"
         required="" autofocus="" name="username">
  <label for="password" class="sr-only">Пароль</label>
  <input type="password" id="password" class="form-control"
         placeholder="Password" required="" name="password">
  <div class="checkbox mb-3">
    <label>
      <input type="checkbox" value="remember-me"> Запомнить меня
    </label>
  </div>
  <button class="btn btn-lg btn-primary btn-block" type="submit">Войти</button>
  <input type="hidden" name="next" value="{% url 'cources:index' %}">
</form>
<p class="mt-5 mb-3 text-muted">© 2020</p>


{% endblock main %}

project/apps/users/templates/users/register.html
{% extends 'appearance/base.html' %}

{% load static %}

{% block main %}

<form method="post" action="{% url 'users:register' %}" class="form-signin" style="margin:30%;">
    {% csrf_token %}
    <h1 class="h3 mb-3 font-weight-normal">Регистриция нового пользователя</h1>
    <label for="username">Логин</label>
    <input type="text" id="username" class="form-control"
         required autofocus="" name="username">
    <label for="password1">Пароль</label>
     <input type="password" id="password1" class="form-control"
            required name="password1">
        <label for="password2">Повторите Пароль</label>
     <input type="password" id="password2" class="form-control"
            required name="password2">
    <label for="first_name">Имя</label>
    <input type="text" id="first_name" class="form-control" name="fisrt_name">
    <label for="last_name">Фамилия</label>
    <input type="text" id="last_name" class="form-control" name="last_name">
    <label for="email">Email</label>
    <input type="email" name="email" required id="email" class="form-control">

    <button name="submit" type="submit">Зарегистрироваться</button>
    <input type="hidden" name="text" value="{% url 'cources:index' %}">
</form>

{% endblock main %}