project/apps/appearance/urls.py
from django.urls import path

from . import views

app_name = 'appearance'

urlpatterns = [
    path('', views.index, name='index'),
    path('personal/', views.personal, name='personal'),
]

project/apps/users/urls.py
from django.urls import path
from django.contrib.auth.views import auth_login

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.index, name="index"),
    path('logout/', views.logout, name='logout'),
    path('authenticate/', views.login, name='login'),
    path('register/', views.register, name='register')
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.shortcuts import render
from django.http import request


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cources/', include("cources.urls", namespace="cources")),
    path('users/', include("users.urls", namespace='users')),
    path('calendar/', include("fullcalendar.urls", namespace="fullcalendar")),
    path('api-auth/', include("rest_framework.urls", namespace="rest_framework")),
    path('', include("appearance.urls", namespace="appearance")),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]

project/apps/appearance/models.py
from django.db import models

# Create your models here.

project/apps/appearance/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404

from cources.models import Faculty, Department, Direction
from users.models import EdenUser


def index(request):
    faculties = Faculty.objects.all()
    departments = Department.objects.all()
    directions = Direction.objects.all()
    context = {
        'faculties':  faculties,
        'departments': departments,
        'directions': directions
    }
    template_name = 'appearance/index.html'
    return render(request, template_name, context)


def personal(request):
    template_name = 'appearance/personal_page.html'

    if request.user.is_authenticated:
        user = request.user
    else:
        raise Http404

    context = {
        'user': user,
    }
    return render(request, template_name, context)


project/apps/appearance/templates/appearance/base.html
{% extends 'appearance/include.html' %}

{% load static %}


{% block main %}

{% block nav %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'appearance:index' %}">EDEN</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'appearance:index' %}">Главная<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'appearance:personal' %}">Личный кабинет</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Календарь
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'fullcalendar:index' %}">Календарь</a>
          <a class="dropdown-item" href="/calendar/events/">Мои события</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="hidden" readonly>
        {% if user.is_authenticated %}
        <a class="nav-link" href="#">Hello, {{ user.username }}</a>
        <a class="btn btn-outline-success my-2 my-sm-0" type="button" href="{% url 'users:logout' %}">Выйти</a>
        {% else %}
         <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
        <a class="btn btn-outline-success my-2 my-sm-0" type="button" href="{% url 'users:index' %}">Войти</a>
        {% endif %}
    </form>
  </div>
</nav>

{% endblock nav %}

<div class="wrapper">
{% block header %}
{% endblock header %}

{% block sidebar1 %}
{% endblock sidebar1 %}


{% block sidebar2 %}
{% endblock sidebar2 %}

<div id="content">
{% block content %}
{% endblock content %}
</div>

</div>

{% block footer %}
{% endblock footer %}

{% endblock main %}

project/apps/appearance/templates/appearance/include.html
{% load static %}
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    <title>EDEN</title>
    {% endblock title %}

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

    {% bootstrap_messages %}

    <link rel="stylesheet" href="{% static 'fullcalendar/core/main.min.css' %}">
    <link rel="stylesheet" href="{% static 'fullcalendar/daygrid/main.min.css' %}">
    <link rel="stylesheet" href="{% static 'fullcalendar/list/main.min.css' %}">
    <link rel="stylesheet" href="{% static 'fullcalendar/timegrid/main.min.css' %}">
    <link rel="stylesheet" href="{% static 'fullcalendar/timeline/main.min.css' %}">
    <link rel="stylesheet" href="{% static 'fullcalendar/resource-timeline/main.min.css' %}">
    <link rel="stylesheet" href="{% static 'fullcalendar/jquery/jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'fullcalendar/jquery/jquery.timepicker.min.css' %}">
    <link rel="stylesheet" href="{% static 'fullcalendar/jquery/jquery.datetimepicker.css' %}">
    <link rel="stylesheet" href="{% static 'fullcalendar/bootstrap/main.min.css' %}">
    <link rel="stylesheet" href="{% static 'fullcalendar/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'appearance/css/style.css' %}">
</head>

<body>

<div class="container">
{% block main %}

    {% block header %}
    {% endblock header %}

    {% block nav %}
    {% endblock nav %}

    {% block sidebar1 %}
    {% endblock sidebar1 %}

    {% block sidebar2 %}
    {% endblock sidebar2 %}

    {% block content %}
    {% endblock content %}

    {% block footer %}
    {% endblock footer %}

{% endblock main %}
</div>




<script src="{% static 'fullcalendar/core/main.min.js' %}"></script>
<script src="{% static 'fullcalendar/daygrid/main.min.js' %}"></script>
<script src="{% static 'fullcalendar/timegrid/main.min.js' %}"></script>
<script src="{% static 'fullcalendar/timeline/main.min.js' %}"></script>
<script src="{% static 'fullcalendar/resource-common/main.min.js' %}"></script>
<script src="{% static 'fullcalendar/resource-timeline/main.min.js' %}"></script>
<script src="{% static 'fullcalendar/interaction/main.min.js' %}"></script>
<script src="{% static 'fullcalendar/jquery/jquery.min.js' %}"></script>
<script src="{% static 'fullcalendar/jquery/jquery-ui.min.js' %}"></script>
<script src="{% static 'fullcalendar/jquery/jquery.timepicker.min.js' %}"></script>
<script src="{% static 'fullcalendar/jquery/jquery.datetimepicker.full.min.js' %}"></script>
<script src="{% static 'fullcalendar/list/main.min.js' %}"></script>
<script src="{% static 'fullcalendar/bootstrap/main.min.js' %}"></script>
<script src="{% static 'fullcalendar/js/main.js' %}"></script>
</body>
</html>

project/apps/appearance/templates/appearance/index.html
{% extends 'appearance/base.html' %}

{% load static %}

{% block header %}
<h1>Главная страница</h1>
{% endblock header %}


{% block sidebar1 %}
<div id="sidebar1" class="aside">

<ul class="sidebar1">
    {% for faculty in faculties %}
    <li>
        <details>
            <summary>{{ faculty }}</summary>
            <ul class="sub-sidebar1">
                {% for department in departments %}

                    {% if department.faculty == faculty %}
                    <li>
                        <details>
                            <summary>{{ department }}</summary>
                            <ul class="sub-sidebar1">
                                {% for direct in directions %}
                                    {% if direct.department == department %}
                                    <li>{{ direct }}</li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </details>
                    </li>
                    {% endif %}

                {% endfor %}
            </ul>
        </details>
    </li>
    {% endfor %}
</ul>

</div>
{% endblock sidebar1 %}


    {% block sidebar2 %}
<div id="sidebar2" class="aside">

    <h2>1914 translation by H. Rackham</h2>
                <p>It is a long established fact that a reader will be distracted by the readable
                content of a page when looking at its layout.</p>
                <h3>Options</h3>
                <ul>
                    <li>Item1</li>
                    <li>Item2</li>
                    <li>Item3</li>
                </ul>

</div>
{% endblock sidebar2 %}



{% block content %}
<p>Контент главной страницы</p>
{% endblock content %}

project/apps/appearance/templates/appearance/personal_page.html
{% extends 'appearance/index.html' %}

{% block sidebar2 %}
<div style="width:100px; heigth:500px; color: green;">
    <p>Важный виджет 1</p>
</div>

<div style="width:100px; heigth:500px; color: blue;">
    <p>Важный виджет 2</p>
</div>

{% endblock sidebar2 %}

{% block content %}
<h1>Hello, {{ user.username }}</h1>
{% endblock content %}